repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: package.lock.json

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.41.0
    hooks:
      - id: ruff
        # args: ['--fix']

  - repo: https://github.com/pycqa/flake8
    rev: v4.0.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88']


