apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
        com.centurylinklabs.watchtower.enable: "true"
    spec:
      containers:
      - name: portfolio
        image: nspeerstra/portfolio:1.1.1
        ports:
        - containerPort: 80
