name: CI - Portfolio Website

on:
  pull_request:

jobs:
  precommit-and-lint:
    if: "!startsWith(github.event.pull_request.title, 'chore(main)')"
    uses: ./.github/workflows/_precommit-and-lint.yml
    with:
      node_version: '20'

  npm-build:
    uses: ./.github/workflows/_npm-build.yml
    needs: precommit-and-lint
    with:
      node_version: '20'

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Download built files (dist)
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Download NGINX config
        uses: actions/download-artifact@v4
        with:
          name: nginx-config
          path: nginx/

      - name: Download Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: dockerfile
          path: .

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
