name: CI - Portfolio Website

on:
  pull_request:

jobs:
  precommit-and-lint:
    if: "!startsWith(github.event.pull_request.title, 'chore(main)')"
    uses: ./.github/workflows/_precommit-and-lint.yml
    with:
      node_version: '20'

  npm-build:
    uses: ./.github/workflows/_npm-build.yml
    needs: precommit-and-lint
    with:
      node_version: '20'

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
