name: Portfolio Website

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: npm install

      - name: Delete Old Branch
        run: |
          git push origin --delete update-changelog || true

      - name: Generate CHANGELOG.md
        run: npm run release -- --skip.bump --skip.tag --skip.commit

      - name: Commit Changes to a Branch
        run: |
          git checkout -b update-changelog
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG.md"

      - name: Push Changes to New Branch
        run: |
          git push origin update-changelog

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore(release): update CHANGELOG.md"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-changelog
          delete-branch: true
          title: "Update CHANGELOG.md"
          body: |
            Update of the CHANGELOG.md file.
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
          labels: changelog

      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

  docker-push:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: changelog
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
