name: Hugo Website CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  precommit-and-lint:
    name: Pre-Commit and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit ruff flake8 detect-secrets

      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Flake8 Linter
        run: flake8 .

  validate-build:
    name: Validate Hugo Build
    runs-on: ubuntu-latest
    needs: precommit-and-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Check for Broken Links
        run: linkchecker public/

      - name: Validate Markdown
        run: markdownlint "**/*.md"

  test-and-build:
    name: Test and Build Hugo Website
    runs-on: ubuntu-latest
    needs: validate-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Website
        run: hugo --gc --minify
