name: CD - Create Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          release-type: node
          package-name: portfolio
